name: AVA: Launch & Operate
on:
  workflow_dispatch:

jobs:
  ok:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Build minimal dashboard
        run: |
          mkdir -p state
          echo "# AVA Dashboard" > state/README.md
          echo "" >> state/README.md
          echo "- Last run (UTC): $(date -u)" >> state/README.md
      - name: Commit dashboard
        run: |
          git config user.name "ava-bot"
          git config user.email "bot@users.noreply.github.com"
          git add state || true
          git commit -m "init dashboard" || true
          git push || true
